### ISSUE TITLE
List of default symbols seems arbitrarily restrictive

### ISSUE THREAD

**Issue by jlherren** [deanilvincent/check-password-strength#59]
By default only the characters `!@#$%^&*` are considered "symbols". I know that this can be overridden as desired, but is there a reason why this list is so restrictive by default? E.g., why are all the following characters not considered symbols? 

    "'()+,-./:;<=>?[]_`{|}~

**Comment by HugoLR** [comment]
Hi @jlherren , how can I override the default regex for symbols?

**Comment by Ennoriel** [comment]
@jlherren @HugoLR Thanks for your feedbacks!

The default parameter value is indeed quite restrictive.
It can be overriden. This should be in the readme.

We haven't figured the best default parameter yet since it varies a lot. And it would result in a breaking changes...
We could use this [OWASP list](https://owasp.org/www-community/password-special-characters). We could also come up with a regexp that is "none letter / digit character" which would also include accentuated letters (éïûñø...). @deanilvincent  any idea?

**Comment by jlherren** [comment]
Yes it would be a breaking change, but perhaps it's something to consider for the next major version. Which characters should be considered symbols is of course somewhat debatable, which is why it makes sense to allow overriding it. But I think most people would agree that `]` should count as a symbol as it certainly increases the password's entropy, as far as brute-force attacks are concerned.

I would have gone with the simple approach of "all ASCII symbols that are not a digit, letter or the space". I think this is almost equivalent to the OWASP list, except they also consider a space to be a symbol.

Whether to also consider non-ASCII Unicode characters is definitely a topic on its own, as it gets really complex there. E.g., is `ä` a symbol or a letter? What about Chinese characters? These are considered letters, but they are neither upper case nor lower case.

**Comment by deanilvincent** [comment]
Hello, everyone.

Thanks for your feedbacks @jlherren @HugoLR! @Ennoriel  and I appreciate you logging issue and possible next feature update. :) 🏅 
Like @Ennoriel mentioned, the symbols can be overridden. We also considering to add the other symbols are part of the default value since the initial and recent versions didn't have those. (I missed to consider those other symbols before, my bad😅)

I agree with @Ennoriel and @jlherren, we could also take the symbols from [OWASP](https://owasp.org/www-community/password-special-characters) list. 
```
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
```
Are there any other symbols that we need to include as part of the changes for the default value (that we may also consider)? :)

**Comment by deanilvincent** [comment]
Closing this issue. : ) New symbols are applied starting version 2.0.5+ Have a good one everyone!
