### ISSUE TITLE
Password strenght special chars

### ISSUE THREAD

**Issue by syco** [deanilvincent/check-password-strength#68]
Hi,

what would be the drawbacks in using this instead?
`^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9])(?=.{10,})`

Thanks

**Comment by Ennoriel** [comment]
Hi @syco 

Thkank you for your issue and using this library.

Your regex is good to test the overall password and tell if it is good or bad according to the options but we would lack the information which rule is ok and which one is not.

Do you have another idea in your mind for asking this question ? ;)

**Comment by syco** [comment]
Yes, the question was, "why do we check for lowercase, uppercase, numbers, and a handful of special chars of the western languages only?"
Instead of checking for lowercase, uppercase, numbers, and any character not in the previous 3 categories?

**Comment by Ennoriel** [comment]
It is purely arbitrary.

In an earlier version, very few special characters were allowed. It has been extended with the characters of this list: https://owasp.org/www-community/password-special-characters.

But it is true that is many language, some characters are considered common, like é, è, à, ï î... One solution could be to open this to allow all characters like you suggested. I don't know if this is a good solution either because there are limitations with non ascii characters on some technologies or software we use daily: https://stackoverflow.com/a/1825824 (I didn't check if the ones we are currently using are ascii).

Do you have an experience with that?

In any case, if we implement it, it should be back compatible :)

**Comment by syco** [comment]
It was just a thought really, to see what implications it would have.
As for the technologies, the only problem I ever had was with the database, but using utf8mb4 solved that.

**Comment by Ennoriel** [comment]
Thanks for your feedback! :)
Do you need it for one of your usecase? I've already thought about it but don't know how to implement it with the back compatibility

**Comment by syco** [comment]
Thanks, but there's no need to implement it.
I'll find a way, it's not important for now.
