### ISSUE TITLE
Angular throws warning for dependency (CommonJS or AMD dependencies can cause optimization bailouts)

### ISSUE THREAD

**Issue by Ronkiro** [deanilvincent/check-password-strength#69]
The error message when using the package inside an angular script is below

> Warning: <path> depends on 'check-password-strength'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Any solutions besides adding it to the "allowlist"?

**Comment by Ennoriel** [comment]
Hi @Ronkiro 

Do you have a minimal reproduction repo that we could start with?

Thanks!

**Comment by Ronkiro** [comment]
@Ennoriel  sorry for the late response, but just need to start any angular v17 project and it will throw this message as a warning

**Comment by Ennoriel** [comment]
Hi again @Ronkiro 

I did try to initialize a repo with:

```sh
npm install -g @angular/cli
ng new angular-project
cd angular-project/
npm i check-password-strength --save
npm start
```

and modified the generated code as follow:

```js
import { passwordStrength } from 'check-password-strength'

// [...]

export class AppComponent {
  title = 'angular-project';

  constructor() {
    console.log(passwordStrength('asdf1234').value)
  }
}
```

but it worked!

I am not familiar with angular anymore. I have not touched it since v5. Before initializing the repo for this issue, I did't know how to initialize a new project and in which conditions you're seeing this error (in a component, in SSR, etc.). Providing a *reproduction repo* will help the maintainers by solving all the above and making it faster for everyone. 😄

**Comment by Ronkiro** [comment]
You did exactly as necessary, nothing else is needed. It does work, but it will throw the **warning** everytime you do `ng serve`. It's not an error, but it tells you that the package will make a hard impact in the final build. Unless you add it to the allowlist, which will make it ignore the warning.

In my case, `acesso` uses it.

![image](https://github.com/deanilvincent/check-password-strength/assets/27526023/92049c4c-ccc5-4130-b2cf-440003ccfbab)


This is the doc's reference from the printscreen: https://angular.io/guide/build#configuring-commonjs-dependencies
